### ISSUE TITLE
BIS_R.R: n <- length(data$group)

### ISSUE THREAD

**Issue by tomWdavies** [Liesefeld/BIS#1]
I am unable to open the example data, so I am unclear on the format the dataframe must be before applying the function. 
The comments say n should be the sample size, and to me this implies that each participant should have one row of data. 
However, this does not seem to make sense with multiple trial types/conditions when the aim is to calculate a BIS for each trial type each participant completed.
Should n be (number of participants) or (number of trial types * number of participants)?

**Comment by Liesefeld** [comment]
Hi! If you're unable to load demoData_R, you can as well use the script below the function. We originally wrote this for between-participants designs, but you can also interpret "group" as "condition" if you use a within-participant design. In the latter case you might find our latest publication on the topic to be of interest: https://doi.org/gr72vt

**Comment by tomWdavies** [comment]
Hi, thanks for your reply, I've got things working now

**Comment by tomWdavies** [comment]
Hi, thanks for your reply, I've got things working now
